In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
df = pd.read_csv('train.txt', sep = ';',header = None, names=['text', 'emotion'])
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [3]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [4]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [5]:
unique_emotion  = df['emotion'].unique()
emotion_number = {}

i = 0
for emo in unique_emotion:
    emotion_number[emo] = i
    i += 1
    
df['emotion'] = df['emotion'].map(emotion_number)

In [6]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [7]:
# converted all text intop lowercase

df['text'] = df['text'].apply(lambda x : x.lower())

In [8]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [9]:
# Removing the panctuation because it destract the model it no meaning the panctuation

import string 

def remove_punc(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [10]:
df['text'] = df['text'].apply(remove_punc)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [11]:
# remove number in the text data because it no meaning in the text columns 

def remove_num(text):
    new = ""
    for i in text:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_num)

df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [12]:
# removeing emoji in dataset then remove it

def remove_emoji(text):
    new = ""
    for i in text:
        if i.isascii():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_emoji)

df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [13]:
# Stopword removeing :It important thing -- it removereing repeated value like (for ,in,is,or, the, of ,and,it,etc) 

import  nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [14]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\deppa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\deppa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
# checking stopword in englsih word 
stop_word = set(stopwords.words('english'))
stop_word

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [16]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [17]:
# removing stop word
def remove(text):
    words = text.split()
    cleaned = []
    for i in words:
        if not i in stop_word:
            cleaned.append(i)
        
    return ' '.join(cleaned)

In [18]:
df['text'] = df['text'].apply(remove)
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [19]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [20]:
# import spacy

# nlp = spacy.load("en_core_web_sm")
# def remove_stopwords_spacy(text):
#     doc = nlp(text)
#     cleaned = []
#     for token in doc:
#         if not token.is_stop and not token.is_punct:
#             cleaned.append(token.text)
#     return ' '.join(cleaned)

In [21]:
# df['text'] = df['text'].apply(remove_stopwords_spacy)

In [22]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [23]:
x = df['text']
y = df['emotion']

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [25]:
X_train

8917     feeling quite pleased fact one coupon use grocery
9453               stressed finally come end feel relieved
2829     feel blessed know immense family supporters co...
9681                       didnt feel like missed anything
12246            feel listless unable imagine ever working
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 10720, dtype: object

In [26]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
12538    feel really ought assert way smiles pleasant b...
6536     even sure formulate thoughts since put feeling...
13806         really feel quite honoured represent country
7724     ive feeling little overwhelmed whole thing lat...
5121     wanting write secret life live one handful peo...
Name: text, Length: 5280, dtype: object

In [27]:
df.shape

(16000, 2)

# Using Bag of word Naive Bay

In [28]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

bow_vectorizer = CountVectorizer()
x_train_bow = bow_vectorizer.fit_transform(X_train)
x_text_bow = bow_vectorizer.transform(X_test)

In [29]:
x_train_bow

<10720x12147 sparse matrix of type '<class 'numpy.int64'>'
	with 96942 stored elements in Compressed Sparse Row format>

In [30]:
x_text_bow

<5280x12147 sparse matrix of type '<class 'numpy.int64'>'
	with 44600 stored elements in Compressed Sparse Row format>

In [31]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [32]:
y_pred_nb = nb_model.predict(x_text_bow)
accuracy_nd = accuracy_score(y_pred_nb,y_test)*100
print("Accuracy of Naive Baye using BOW :",accuracy_nd)

Accuracy of Naive Baye using BOW : 76.47727272727273

In [33]:
y_pred_nb

array([0, 5, 0, ..., 5, 4, 0], dtype=int64)

In [34]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
12538    5
6536     4
13806    5
7724     4
5121     0
Name: emotion, Length: 5280, dtype: int64

# Using TF -IDF Logistic Regression

In [35]:

tf_vectorizer = TfidfVectorizer()
x_train_tf = tf_vectorizer.fit_transform(X_train)
x_text_tf = tf_vectorizer.transform(X_test)

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

tf_model = LogisticRegression()
tf_model.fit(x_train_tf,y_train)

LogisticRegression()

In [37]:
y_pred_tf = tf_model.predict(x_text_bow)
accuracy_tf = accuracy_score(y_pred_tf,y_test)*100
print("Accuracy of Naive Baye using BOW :",accuracy_tf)

Accuracy of Naive Baye using BOW : 85.09469696969697

In [38]:
y_pred_tf[0:10]

array([0, 5, 0, 5, 0, 0, 4, 0, 2, 4], dtype=int64)

In [39]:
y_test[0:10]

8756    0
4660    5
6095    0
304     5
8241    0
9577    0
1035    4
9976    0
7872    2
8341    4
Name: emotion, dtype: int64

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

lr = LogisticRegression()
nb = MultinomialNB()
svm = SVC(probability=True)

voting = VotingClassifier(
    estimators=[
        ('lr', lr),
        ('nb', nb),
        ('svm', svm)
    ],
    voting='soft'
)

voting.fit(X_train_vec, y_train)
y_pred = voting.predict(X_test_vec)

In [41]:
accuracy_score(y_pred,y_test)*100

88.01136363636364

In [ ]:
# voting.fit(X_train_vec, y_train)

# 🔹 Accuracy check
models = {
    "Logistic Regression": lr,
    "Naive Bayes": nb,
    "SVM": svm,
    "Voting Ensemble": voting
}

for name, model in models.items():
    model.fit(X_train_vec,y_train)
    y_pred = model.predict(X_test_vec)
    print(name, "accuracy:", accuracy_score(y_test, y_pred))

Logistic Regression accuracy: 0.887689393939394
Naive Bayes accuracy: 0.7647727272727273
SVM accuracy: 0.8162878787878788
Voting Ensemble accuracy: 0.8797348484848485